### ISSUE TITLE
Can't install on windows10

### ISSUE THREAD

**Issue by llHoYall** [nicolaspanel/node-svm#47]
If I try to install on windows 10, it has error.

```
$ npm i node-svm
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js

> node-svm@2.1.8 install C:\Users\hoya1\hWorkspace\AI_Playground\MNIST_React\node_modules\node-svm
> node-gyp rebuild


C:\Users\hoya1\hWorkspace\AI_Playground\MNIST_React\node_modules\node-svm>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  svm.cpp
  addon.cc
  node-svm.cc
  win_delay_load_hook.cc
c:\users\hoya1\hworkspace\ai_playground\mnist_react\node_modules\node-svm\src\node-svm/node-svm.h(88): warning C4244: '=': conversion f rom 'int64_t' to 'int', possible loss of data (compiling source file ..\src\addon.cc) [C:\Users\hoya1\hWorkspace\AI_Playground\MNIST_Re act\node_modules\node-svm\build\addon.vcxproj]
c:\users\hoya1\hworkspace\ai_playground\mnist_react\node_modules\node-svm\src\node-svm/node-svm.h(125): warning C4244: '=': conversion
from 'int64_t' to 'int', possible loss of data (compiling source file ..\src\addon.cc) [C:\Users\hoya1\hWorkspace\AI_Playground\MNIST_R eact\node_modules\node-svm\build\addon.vcxproj]
c:\users\hoya1\hworkspace\ai_playground\mnist_react\node_modules\node-svm\src\node-svm/node-svm.h(137): warning C4244: '=': conversion
from 'int64_t' to 'int', possible loss of data (compiling source file ..\src\addon.cc) [C:\Users\hoya1\hWorkspace\AI_Playground\MNIST_R eact\node_modules\node-svm\build\addon.vcxproj]
c:\users\hoya1\hworkspace\ai_playground\mnist_react\node_modules\node-svm\src\node-svm/node-svm.h(212): warning C4244: '=': conversion
from 'int64_t' to 'int', possible loss of data (compiling source file ..\src\addon.cc) [C:\Users\hoya1\hWorkspace\AI_Playground\MNIST_R eact\node_modules\node-svm\build\addon.vcxproj]
c:\users\hoya1\hworkspace\ai_playground\mnist_react\node_modules\node-svm\src\node-svm/node-svm.h(216): warning C4244: '=': conversion
from 'int64_t' to 'int', possible loss of data (compiling source file ..\src\addon.cc) [C:\Users\hoya1\hWorkspace\AI_Playground\MNIST_R eact\node_modules\node-svm\build\addon.vcxproj]
c:\users\hoya1\hworkspace\ai_playground\mnist_react\node_modules\node-svm\src\node-svm/node-svm.h(243): warning C4244: '=': conversion
from 'int64_t' to 'int', possible loss of data (compiling source file ..\src\addon.cc) [C:\Users\hoya1\hWorkspace\AI_Playground\MNIST_R eact\node_modules\node-svm\build\addon.vcxproj]
c:\users\hoya1\hworkspace\ai_playground\mnist_react\node_modules\node-svm\src\node-svm/node-svm.h(256): warning C4244: '=': conversion
from 'int64_t' to 'int', possible loss of data (compiling source file ..\src\addon.cc) [C:\Users\hoya1\hWorkspace\AI_Playground\MNIST_R eact\node_modules\node-svm\build\addon.vcxproj]
c:\users\hoya1\hworkspace\ai_playground\mnist_react\node_modules\node-svm\src\node-svm\node-svm.h(88): warning C4244: '=': conversion f rom 'int64_t' to 'int', possible loss of data (compiling source file ..\src\node-svm\node-svm.cc) [C:\Users\hoya1\hWorkspace\AI_Playgro und\MNIST_React\node_modules\node-svm\build\addon.vcxproj]
c:\users\hoya1\hworkspace\ai_playground\mnist_react\node_modules\node-svm\src\node-svm\node-svm.h(125): warning C4244: '=': conversion
from 'int64_t' to 'int', possible loss of data (compiling source file ..\src\node-svm\node-svm.cc) [C:\Users\hoya1\hWorkspace\AI_Playgr ound\MNIST_React\node_modules\node-svm\build\addon.vcxproj]
c:\users\hoya1\hworkspace\ai_playground\mnist_react\node_modules\node-svm\src\node-svm\node-svm.h(137): warning C4244: '=': conversion
from 'int64_t' to 'int', possible loss of data (compiling source file ..\src\node-svm\node-svm.cc) [C:\Users\hoya1\hWorkspace\AI_Playgr ound\MNIST_React\node_modules\node-svm\build\addon.vcxproj]
c:\users\hoya1\hworkspace\ai_playground\mnist_react\node_modules\node-svm\src\node-svm\node-svm.h(212): warning C4244: '=': conversion
from 'int64_t' to 'int', possible loss of data (compiling source file ..\src\node-svm\node-svm.cc) [C:\Users\hoya1\hWorkspace\AI_Playgr ound\MNIST_React\node_modules\node-svm\build\addon.vcxproj]
c:\users\hoya1\hworkspace\ai_playground\mnist_react\node_modules\node-svm\src\node-svm\node-svm.h(216): warning C4244: '=': conversion
from 'int64_t' to 'int', possible loss of data (compiling source file ..\src\node-svm\node-svm.cc) [C:\Users\hoya1\hWorkspace\AI_Playgr ound\MNIST_React\node_modules\node-svm\build\addon.vcxproj]
c:\users\hoya1\hworkspace\ai_playground\mnist_react\node_modules\node-svm\src\node-svm\node-svm.h(243): warning C4244: '=': conversion
from 'int64_t' to 'int', possible loss of data (compiling source file ..\src\node-svm\node-svm.cc) [C:\Users\hoya1\hWorkspace\AI_Playgr ound\MNIST_React\node_modules\node-svm\build\addon.vcxproj]
c:\users\hoya1\hworkspace\ai_playground\mnist_react\node_modules\node-svm\src\node-svm\node-svm.h(256): warning C4244: '=': conversion
from 'int64_t' to 'int', possible loss of data (compiling source file ..\src\node-svm\node-svm.cc) [C:\Users\hoya1\hWorkspace\AI_Playgr ound\MNIST_React\node_modules\node-svm\build\addon.vcxproj]
c:\users\hoya1\hworkspace\ai_playground\mnist_react\node_modules\node-svm\src\node-svm\training-worker.h(38): warning C4996: 'Nan::Call back::Call': was declared deprecated (compiling source file ..\src\node-svm\node-svm.cc) [C:\Users\hoya1\hWorkspace\AI_Playground\MNIST _React\node_modules\node-svm\build\addon.vcxproj]
  C:\Users\hoya1\hWorkspace\AI_Playground\MNIST_React\node_modules\nan\nan.h(1618): note: see declaration of 'Nan::Callback::Call' (com
  piling source file ..\src\node-svm\node-svm.cc)
c:\users\hoya1\hworkspace\ai_playground\mnist_react\node_modules\node-svm\src\node-svm\prediction-worker.h(36): warning C4996: 'Nan::Ca llback::Call': was declared deprecated (compiling source file ..\src\node-svm\node-svm.cc) [C:\Users\hoya1\hWorkspace\AI_Playground\MNI ST_React\node_modules\node-svm\build\addon.vcxproj]
  C:\Users\hoya1\hWorkspace\AI_Playground\MNIST_React\node_modules\nan\nan.h(1618): note: see declaration of 'Nan::Callback::Call' (com
  piling source file ..\src\node-svm\node-svm.cc)
c:\users\hoya1\hworkspace\ai_playground\mnist_react\node_modules\node-svm\src\node-svm\probability-prediction-worker.h(46): warning C49 96: 'Nan::Callback::Call': was declared deprecated (compiling source file ..\src\node-svm\node-svm.cc) [C:\Users\hoya1\hWorkspace\AI_Pl ayground\MNIST_React\node_modules\node-svm\build\addon.vcxproj]
  C:\Users\hoya1\hWorkspace\AI_Playground\MNIST_React\node_modules\nan\nan.h(1618): note: see declaration of 'Nan::Callback::Call' (com
  piling source file ..\src\node-svm\node-svm.cc)
..\src\node-svm\node-svm.cc(37): error C2661: 'v8::Function::NewInstance': no overloaded function takes 2 arguments [C:\Users\hoya1\hWo rkspace\AI_Playground\MNIST_React\node_modules\node-svm\build\addon.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\hoya1\hWorkspace\AI_Playground\MNIST_React\node_modules\node-svm
gyp ERR! node -v v10.3.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN mnist_react@1.0.0 No description
npm WARN mnist_react@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-svm@2.1.8 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-svm@2.1.8 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

Help me...

Windows10
Major  Minor  Build  Revision
-----  -----  -----  --------
10       0      17134  0

node v10.3.0
npm v6.1.0
node-gyp v3.8.0 (my installed version is different with messages)
python v2.7.15
.NET v4.6.2

**Comment by llHoYall** [comment]
On MAC, installation with node 10 is failure and with node 8 is success.
Is it a bug with node 10?
On Windows, I will try this.

**Comment by nicolaspanel** [comment]
Should be ok now
